apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/bitcoin-price-salil/backend:latest # Replace with your Docker image path
        ports:
        - containerPort: 5000

